# -*- coding: utf-8 -*-
"""박수지_1145_최종과제_제출 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hg4EhKTjiCUAW86A791qkMU8UwdB4E8M

# 1. 문제 정의

본 분석의 목적은 조별활동 이탈(group_leave)에 영향을 미치는 요인을 분석하고,
이를 기반으로 조편성 전략을 제안하는 것이다.

# 2. 데이터 불러오기 및 기초 점검
"""

# 기본 라이브러리
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


!pip install koreanize-matplotlib -q
import koreanize_matplotlib

import warnings
warnings.filterwarnings('ignore')

plt.rcParams['figure.figsize'] = (8,5)
sns.set_style("whitegrid")

# 파일 연결
import pandas as pd
df = pd.read_csv('/content/bda11 - analysis_final.csv', encoding='utf-8')

# 한글 폰트 설치
!apt-get install -y fonts-nanum

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 폰트 적용
plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

"""데이터 구조 및 결측치를 확인한다.




"""

df = pd.read_csv('bda11 - analysis_final.csv')
df.info()
df.describe()
df.isnull().mean().sort_values(ascending=False)

"""결측치 분석 결과,
핵심 분석 변수(score_q, on_offline, leader_left 등)는
결측률이 5% 이하로 낮게 나타나 분석에 큰 문제가 없었다.

다만, major1_2와 job_domain 변수는 결측률이 30% 이상으로 높아
본 분석에서는 핵심 변수로 사용하지 않았다.

# 3. 기초 분석
## 3.1 전체 이탈 비율
"""

df['group_leave'].value_counts(normalize=True)

leave_rate = df['group_leave'].value_counts(normalize=True)

labels = ['유지', '이탈']

plt.figure(figsize=(5,5))
plt.pie(leave_rate.values,
        labels=labels,
        autopct='%1.1f%%',
        startangle=90)
plt.title('전체 이탈 비율')
plt.show()

"""이탈 비율을 시각적으로 확인한다.

"""

sns.countplot(x='group_leave', data=df)
plt.title("")
plt.show()

# 참여 방식별 전체 인원 수
df['on_offline'].value_counts()

# 참여 방식별 조장 수
df[df['group_master']==1]['on_offline'].value_counts()

# 참여 방식별 이탈 건수
df[df['group_leave']==1]['on_offline'].value_counts()

"""# 4. 구조 리스크 정의

조장이 이탈한 조를 구조 리스크 조로 정의한다.
"""

leader_dropout_groups = df[
    (df['group_master'] == 1) & (df['group_leave'] == 1)
][['generation','class_code','group_number']]

df['leader_left'] = df.set_index(
    ['generation','class_code','group_number']
).index.isin(
    leader_dropout_groups.set_index(
        ['generation','class_code','group_number']
    ).index
).astype(int)

df['leader_left'].mean()

"""# 4. 분위수 분석
초기 점수(avg_point_m1m2)를 기준으로 4분위로 구분한다.

"""

df['score_q'] = pd.qcut(df['avg_point_m1m2'], 4, labels=False)
df.groupby('score_q')['group_leave'].mean()

sns.barplot(x='score_q', y='group_leave', data=df)
plt.title("초기 점수 이탈률 분위별")
plt.show()

"""초기 점수 하위 분위에서 이탈률이 높은지 확인한다.

# 5. 이상치 제거 (IQR 방식)
"""

Q1 = df['avg_point_m1m2'].quantile(0.25)
Q3 = df['avg_point_m1m2'].quantile(0.75)
IQR = Q3 - Q1

df_clean = df[
    (df['avg_point_m1m2'] >= Q1 - 1.5*IQR) &
    (df['avg_point_m1m2'] <= Q3 + 1.5*IQR)
]

print("Before:", df['group_leave'].mean())
print("After:", df_clean['group_leave'].mean())

"""이상치 제거 전후 이탈률 변화를 비교한다.

# 6. 개인 이탈 리스크 분석

## 6.1 참여 방식별 이탈률
"""

df.groupby('on_offline')['group_leave'].mean()

sns.barplot(x='on_offline', y='group_leave', data=df)
plt.title("참여 방식별 이탈률")
plt.show()

"""## 6.2 반복그룹화

"""

# 1) score_q × on_offline
pd.pivot_table(
    df,
    values='group_leave',
    index='score_q',
    columns='on_offline',
    aggfunc='mean'
)

# 2) score_q × has_leader
pd.pivot_table(
    df,
    values='group_leave',
    index='score_q',
    columns='has_leader',
    aggfunc='mean'
)

# 3) on_offline × has_leader
pd.pivot_table(
    df,
    values='group_leave',
    index='on_offline',
    columns='has_leader',
    aggfunc='mean'
)

"""6.4 연령 다양성 분위수 분석"""

df['age_sd_q'] = pd.qcut(df['age_sd'], 4, labels=False)

df.groupby('age_sd_q')['group_leave'].mean()

df.sample(200).to_csv("sample_data.csv", index=False)

"""6.5 직무 다양성 분석

# 7. 구조 리스크 분석 (조장 이탈 중심)
"""

# 조장 이탈률
df[df['group_master']==1]['group_leave'].mean()

# 온라인/오프라인별 조장 이탈
df[df['group_master']==1].groupby('on_offline')['group_leave'].mean()

# 초기 점수 분위수별 조장 이탈
df[df['group_master']==1].groupby('score_q')['group_leave'].mean()

"""##조장 이탈의 원인 분석"""

df[df['group_master']==1].groupby('score_q')['group_leave'].mean()
df[df['group_master']==1].groupby('on_offline')['group_leave'].mean()
df[df['group_master']==1].groupby('age_sd_q')['group_leave'].mean()

"""##조장 이탈이 실제로 파괴적 영향이 있는가?"""

df.groupby('leader_left')['group_leave'].mean()

"""#가설검증
##1.초기 점수
하위 25% → 이탈률 약 17~18%

상위 구간 → 8~9%

✔ 가장 일관된 패턴  
✔ 개인 리스크 + 조장 리스크 모두와 연결됨  
→ 근본 원인 후보

##2.온라인 vs 오프라인

온라인 이탈률 ≈ 15%

오프라인 ≈ 8%

✔ 표본도 충분  
✔ 거의 2배 차이

→ 환경 요인으로 작동 가능

##3.3번 축: 조장 이탈 (구조 리스크)

조장 이탈 발생 시 전체 이탈률 55%

미발생 조는 8%

✔ 가장 “파괴적 영향” 변수  
✔ 그러나 원인이라기보다 “증폭 요인”
"""

# 참여 방식별 초기 점수 평균
df.groupby('on_offline')['avg_point_m1m2'].mean()

#시각화
sns.boxplot(x='on_offline', y='avg_point_m1m2', data=df)
plt.title("참여방식별 초기 점수 평균")
plt.show()

#분위수 분포 비교우선
pd.crosstab(df['on_offline'], df['score_q'], normalize='index')

"""#가설검증

H1: 초기 점수 분위수와 이탈 여부는 독립이다.  
H2: 참여 방식(온라인/오프라인)과 이탈 여부는 독립이다.  
H3: 조장 이탈 발생 여부와 전체 이탈은 독립이다.  

  


---



귀무가설(H0): 두 변수는 독립이다.  
대립가설(H1): 두 변수는 독립이 아니다.

##H1 – 초기 점수와 이탈 (카이제곱)
"""

import scipy.stats as stats

# 교차표
ct1 = pd.crosstab(df['score_q'], df['group_leave'])

chi2_1, p_1, dof_1, exp_1 = stats.chi2_contingency(ct1)

print("H1 Chi-square:", chi2_1)
print("H1 p-value:", p_1)

"""##H2 – 온라인 vs 오프라인"""

import scipy.stats as stats

df_h2 = df[df['on_offline'].isin(['온라인','오프라인'])]

ct2 = pd.crosstab(df_h2['on_offline'], df_h2['group_leave'])

chi2_2, p_2, dof_2, exp_2 = stats.chi2_contingency(ct2)

print("H2 Chi-square:", chi2_2)
print("H2 p-value:", p_2)

"""##H3 – 조장 이탈과 전체 이탈"""

ct3 = pd.crosstab(df['leader_left'], df['group_leave'])

chi2_3, p_3, dof_3, exp_3 = stats.chi2_contingency(ct3)

print("H3 Chi-square:", chi2_3)
print("H3 p-value:", p_3)

"""##결과 해석

## H1: 초기 점수와 이탈

카이제곱 검정 결과  
Chi-square = 18.76  
p-value = 0.000306  

p-value < 0.01로 나타나 귀무가설을 기각한다.  
초기 점수 분위수와 이탈 여부 사이에는 통계적으로 유의한 관계가 존재한다.  
특히 하위 분위에서 이탈률이 높게 나타났다.

---

## H2: 온라인 vs 오프라인

Chi-square = 12.13  
p-value = 0.000495  

p-value < 0.01로 나타나 귀무가설을 기각한다.  
참여 방식과 이탈 여부는 통계적으로 유의한 관계가 있다.  
온라인 참여자의 이탈률이 오프라인보다 높게 나타났다.

---

## H3: 조장 이탈과 전체 이탈

Chi-square = 229.38  
p-value ≈ 8.1e-52  

극도로 낮은 p-value로 귀무가설을 강하게 기각한다.  
조장 이탈은 조 전체 이탈과 매우 강한 연관을 가진다.  
조장 이탈이 발생한 조에서 이탈률이 급격히 증가하였다.

#로지스틱 회귀 분석

종속변수(group_leave)는 이탈 여부(0/1)로 구성된 이진 변수이므로,
연속형 종속변수를 가정하는 선형회귀 대신
이탈 확률을 직접 모델링할 수 있는 로지스틱 회귀를 적용하였다.

종속변수: group_leave  
독립변수: score_q, on_offline, leader_left

##8.1 데이터 전처리 (더미변수 생성)
"""

import statsmodels.api as sm
import pandas as pd

# df에서 필요한 컬럼(score_q, on_offline, group_leave, leader_left)을 선택하여 df_model 생성
# score_q는 이미 df에 추가되어 있어야 함 (f_FvHyyl0uB2 셀 확인)
df_model = df[['score_q', 'on_offline', 'group_leave', 'leader_left']].copy()

# '온라인' 또는 '오프라인' 참여 방식만 필터링
df_model = df_model[df_model['on_offline'].isin(['온라인','오프라인'])]

# 결측치 제거
# score_q는 avg_point_m1m2의 NaN으로 인해 NaN이 될 수 있으므로 제거
# group_leave, on_offline, leader_left 컬럼에도 NaN이 없어야 함
df_model.dropna(subset=['score_q', 'on_offline', 'group_leave', 'leader_left'], inplace=True)

# 온라인/오프라인 더미 변수 생성
df_model = pd.get_dummies(df_model, columns=['on_offline'], drop_first=True)

# 독립변수 설정 for Model 1
X1 = df_model[['score_q', 'on_offline_온라인']]
X1 = sm.add_constant(X1)

# 종속변수 설정
y = df_model['group_leave']

"""##8.2 모델 1 (초기 점수 + 온라인)"""

# 불리언 종속변수를 정수(0 또는 1)로 변환
y_numeric = y.astype(int)

# X1 DataFrame의 불리언 컬럼을 정수(0 또는 1)로 변환
X1_numeric = X1.copy() # 원본 X1을 변경하지 않기 위해 복사본 사용
if 'on_offline_온라인' in X1_numeric.columns and X1_numeric['on_offline_온라인'].dtype == 'bool':
    X1_numeric['on_offline_온라인'] = X1_numeric['on_offline_온라인'].astype(int)

model1 = sm.Logit(y_numeric, X1_numeric).fit()
print(model1.summary())

"""##8.3 모델 2 (조장 이탈 포함)"""

X2 = df_model[['score_q', 'on_offline_온라인', 'leader_left']]
X2 = sm.add_constant(X2)

# 종속변수 y를 숫자형으로 변환
y_numeric = y.astype(int)

# 독립변수 X2에서 불리언 컬럼을 숫자형으로 변환 (만약 있다면)
X2_numeric = X2.copy()
if 'on_offline_온라인' in X2_numeric.columns and X2_numeric['on_offline_온라인'].dtype == 'bool':
    X2_numeric['on_offline_온라인'] = X2_numeric['on_offline_온라인'].astype(int)
# leader_left도 혹시 모를 불리언 타입을 위해 명시적으로 int로 변환
if 'leader_left' in X2_numeric.columns and X2_numeric['leader_left'].dtype == 'bool':
    X2_numeric['leader_left'] = X2_numeric['leader_left'].astype(int)

model2 = sm.Logit(y_numeric, X2_numeric).fit()
print(model2.summary())

# 개인정보 컬럼 제거
cols_to_drop = [
    'member_id',
    'birthday',
    'birth_date',
    'age',
    'major1_1',
    'major1_2',
    'job_domain'
]

df_public = df.drop(columns=cols_to_drop)

# 혹시 남은 object형 민감정보 있는지 확인
print(df_public.select_dtypes(include='object').columns)

# 공개용 CSV 저장
df_public.to_csv("analysis_public_sample.csv", index=False)

df_public.sample(300, random_state=42).to_csv(
    "analysis_public_sample.csv",
    index=False
)

import numpy as np

# 오즈비 계산
params = model2.params
conf = model2.conf_int()

# 오즈비와 신뢰구간 변환
odds_ratio = np.exp(params)
conf['OR_lower'] = np.exp(conf[0])
conf['OR_upper'] = np.exp(conf[1])

result_table = pd.DataFrame({
    'Odds Ratio': odds_ratio,
    'Lower 95% CI': conf['OR_lower'],
    'Upper 95% CI': conf['OR_upper'],
    'p-value': model2.pvalues
})

result_table

"""# 9. 의사결정나무 분석

이탈 발생 조건을 직관적으로 확인하기 위해
의사결정나무 분류 모델을 적용한다.

종속변수: group_leave  
독립변수: score_q, on_offline, leader_left
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree
import matplotlib.pyplot as plt

# 분석용 데이터 준비
df_tree = df.copy()
df_tree = df_tree[df_tree['on_offline'].isin(['온라인','오프라인'])]

df_tree = pd.get_dummies(df_tree, columns=['on_offline'], drop_first=True)

X = df_tree[['score_q', 'on_offline_온라인', 'leader_left']]
y = df_tree['group_leave']

# 학습/테스트 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

#모델학습
clf = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

clf.fit(X_train, y_train)

plt.figure(figsize=(12,6))
tree.plot_tree(
    clf,
    feature_names=X.columns,
    class_names=["stay","leave"],
    filled=True
)
plt.show()

"""# . 상관 분석

"""

num_cols = [
    'age',
    'avg_point_m1m2',
    'delta_m2_m1',
    'group_size',
    'age_sd',
    'job_domain_cnt',
    'major_cnt'
]

corr = df[num_cols + ['group_leave']].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()